### ISSUE TITLE
Create note

### ISSUE THREAD

**Issue by SaraabbasiNZ** [SaraabbasiNZ/react-note-app#1]
As a **user** I want to **create a new note** so that I can ** store my ideas or tasks.**

### Acceptance Criteria:
  
- [x] I can input a title and body text for the note.
- [x] The note is saved with the current date and time.

### Tasks
 
- [x] Create a form in React to input the note’s title and body
- [x] Set up a Django API endpoint for creating notes.
- [x] Store the creation and update timestamps in the Django model.

**Comment by SaraabbasiNZ** [comment]
9/22/2024
