### ISSUE TITLE
Delete note

### ISSUE THREAD

**Issue by SaraabbasiNZ** [SaraabbasiNZ/react-note-app#3]
As a **user** I want to **delete a note** so that I can **remove notes I no longer need.**

### Acceptance Criteria:
  
- [ ]  I can delete a note from the note list.
- [ ] I receive a confirmation before the note is permanently deleted.

### Tasks
 
- [ ] Add a delete button to each note in the note list in React.
- [ ] Add a confirmation dialog before deleting the note.
- [ ] Connect the delete button to the API to remove the note.
