### ISSUE TITLE
View list of all notes

### ISSUE THREAD

**Issue by SaraabbasiNZ** [SaraabbasiNZ/react-note-app#4]
As a **user** I want to **view a list of all notes ** so that I can **quickly see and access my stored information.**

### Acceptance Criteria:
  
- [ ]  I can view all my notes in a list with their titles and categories.
- [ ] Each note displays the creation and last updated date.

### Tasks
 
- [ ] Create a list view in React to display all notes.
- [ ] Fetch notes from the Django API and display them with titles, categories, and timestamps.
