### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by SaraabbasiNZ** [SaraabbasiNZ/react-note-app#7]
As a **user** I want to **receive error messages** when trying to input invalid data so that I can ** correct my input.**

### Acceptance Criteria:
  
- [ ] I receive an error if I try to save a note without a title.

### Tasks
 
- [ ] Add form validation logic in React to ensure all required fields are filled.
- [ ] Validate data on the backend in Django to prevent invalid note creation.
